/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */

export default {
    'interface': {
        'en': {
            'ds18b20.name': 'DS18B20 Sensor',
            'ds18b20.description': 'Single bus digital temperature sensor based on DS18B20.'
        },
        'ru': {
            'ds18b20.name': 'DS18B20 Sensor',
            'ds18b20.description': 'Single bus digital temperature sensor based on DS18B20.'
        },
        'zh-cn': {
            'ds18b20.name': 'DS18B20 Sensor',
            'ds18b20.description': 'Single bus digital temperature sensor based on DS18B20.'
        },
        'zh-tw': {
            'ds18b20.name': 'DS18B20 Sensor',
            'ds18b20.description': 'Single bus digital temperature sensor based on DS18B20.'
        }
    },
    'extensions': {
        'en': {},
        'ru': {},
        'zh-cn': {},
        'zh-tw': {}
    },
    'blocks': {
        'en': {
            'DS18B20_CATEGORY': 'DS18B20',
            'DS18B20_INIT': 'init ds18b20 pin %1 quantity %2',
            'DS18B20_READALLTEMPERATURES': 'ds18b20 read all temperatures',
            'DS18B20_GETTEMPERATURE': 'ds18b20 %1 temperatures %2'
        },
        'ru': {
            'DS18B20_CATEGORY': 'DS18B20',
            'DS18B20_INIT': 'init ds18b20 pin %1 quantity %2',
            'DS18B20_READALLTEMPERATURES': 'ds18b20 read all temperatures',
            'DS18B20_GETTEMPERATURE': 'ds18b20 %1 temperatures %2'
        },
        'zh-cn': {
            'DS18B20_CATEGORY': 'DS18B20',
            'DS18B20_INIT': 'init ds18b20 pin %1 quantity %2',
            'DS18B20_READALLTEMPERATURES': 'ds18b20 read all temperatures',
            'DS18B20_GETTEMPERATURE': 'ds18b20 %1 temperatures %2'
        },
        'zh-tw': {
            'DS18B20_CATEGORY': 'DS18B20',
            'DS18B20_INIT': 'init ds18b20 pin %1 quantity %2',
            'DS18B20_READALLTEMPERATURES': 'ds18b20 read all temperatures',
            'DS18B20_GETTEMPERATURE': 'ds18b20 %1 temperatures %2'
        }
    }
};
